stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - anecdotes.csv
    params:
      - train
    outs:
      - model.pkl
    metrics:
      - metrics.txt:
          cache: false