package main

import (
	"net/http"

	_ "github.com/SlayerSv/SFU-IKIT/integration/pr4/server/docs" // Generated by swag init

	httpSwagger "github.com/swaggo/http-swagger"
)

func (app *App) NewRouter() http.Handler {
	router := http.NewServeMux()
	router.HandleFunc("GET /currencies", app.Auth(app.GetCurrencies))
	router.HandleFunc("GET /currencies/count", app.Auth(app.GetCurrencyCount))
	router.HandleFunc("GET /currencies/{code}", app.Auth(app.GetCurrencyByCode))
	router.HandleFunc("GET /currencies/updated_at", app.Auth(app.UpdatedAt))
	router.HandleFunc("POST /currencies", app.Auth(app.AddCurrency))

	router.HandleFunc("GET /api_key", app.GetAPIKey)

	router.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	return app.Middleware(router)
}
