services:
    server:
        build:
            dockerfile: server/Dockerfile
        ports:
            - "8080:8080"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PORT=:8080
            - GRPC_PORT=:50051
            - KAFKA_ADDR=kafka:9092
            - KAFKA_TOPIC=new_currencies
        depends_on:
            - kafka
            - postgres
        networks:
            - currency-api-network
      
    client:
        build:
            dockerfile: client/Dockerfile
        environment:
            - SERVER_GRPC_ADDR=server:50051
            - KAFKA_ADDR=kafka:9092
            - KAFKA_TOPIC=new_currencies
        depends_on:
            - server
            - kafka
        networks:
            - currency-api-network
  
    postgres:
        image: postgres:17-alpine
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=currencies
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./server/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
        networks:
            - currency-api-network

    kafka:
        image: apache/kafka:4.0.0
        ports:
            - 9093:9092
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_LOG_DIRS: /var/lib/kafka/data
        volumes:
            - kafka-data:/var/lib/kafka/data
        networks:
            - currency-api-network

networks:
    currency-api-network:
        driver: bridge

volumes:
    pgdata:
    kafka-data: